### ISSUE TITLE
Debugging mode

### ISSUE THREAD

**Issue by IanMayo** [serge-web/map#17]
I think that at least once, and maybe repeatedly, we should aim to verify the coordinates provided by the map match those that were clicked on.

Beyond that, there may be instances when messages refer to hex cells. Ideally spatially-related messages will, at some point in the future, allow a marker to be displayed on the map (sea-mine found, stranded yacht, etc).  But, until then, _maybe_ the UI should allow hex cell id numbers (coordinates) to be displayed - possibly via a checkbox.

**Comment by BMPMS** [comment]
Markers and paths are always placed on the hex map relating the hex id (row-column).  They always match because all the clicks are related to the hex’s which have their set id.  Their ‘center' is defined and stored on initialise  and is always accessed via the same function (get_points).  

Should the map be redrawn (potentially on window resize), the new ‘center’ points can be stored and we are ready to go.

What I do need to do (doing now) is to make all instances of placing the icon in one function as there is an offset from the center which is currently repeated a couple of times (and has caused the error).  Slap on the wrist, sorted.

It would be a 10 minute job to add a function to place a marker on a given hex.
